FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime
RUN apt-get update -y\
    && apt-get install make -y\
    && apt-get install build-essential -y
COPY requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt
